LittlerootTown_Text_IfYouGoIntoGrassPokemonWillPopOut::
	.string "If you go into the tall grass, wild\n"
	.string "POKeMON will pop out!$"

LittlerootTown_Text_GoodLuck::
	.string "Good luck on your adventure!$"

LittlerootTown_Text_YouSavedBirch::
	.string "You saved PROF. BIRCH!\n"
	.string "You're amazing!$"

LittlerootTown_Text_GoSaveBirch::
	.string "PROF. BIRCH is in trouble!\n"
	.string "Go save him!$"

LittlerootTown_Text_CanUsePCToStoreItems::
	.string "If you use a PC, you can store items\n"
	.string "and POKeMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_BirchSpendsDaysInLab::
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying POKeMON.$"

LittlerootTown_Text_OurNewHomeLetsGoInside::
	.string "MOM: Look, {PLAYER}!\n"
	.string "It's our new home!\p"
	.string "It must be tiring riding with our things\n"
	.string "in the moving truck.\p"
	.string "Come on, lets go inside.$"

LittlerootTown_Text_BirchSomethingToShowYouAtLab::
	.string "PROF. BIRCH has something to show you\n"
	.string "at his POKeMON LAB.$"

LittlerootTown_Text_GachaNotReadyText::
	.string "Ich bereite meine Gacha-Maschine noch\n"
	.string "vor. Komm spaeter wieder!$"

LittlerootTown_Text_GachaJackpot::
	.string "Unglaublich! Du hast den Hauptgewinn\n"
	.string "gezogen! Ein Pokemon!$"

LittlerootTown_Text_GachaRefuse::
	.string "Schade... Komm wieder, wenn du Lust\n"
	.string "auf ein Risiko hast!$"

LittlerootTown_Text_GachaNoBerryText::
	.string "Du hast keine Beere ausgewaehlt.$"

LittlerootTown_Text_GachaReceiveMon::
	.string "{PLAYER} erhaelt das Pokemon!$"

LittlerootTown_Text_GachaMonSentPC::
	.string "Das Pokemon wurde auf den PC\n"
	.string "uebertragen.$"

LittlerootTown_Text_GachaBoxFull::
	.string "Deine PC-Boxen sind voll?!$"

LittlerootTown_Text_StyleChanger::
	.string "I cannot change your style right now!$"

LittlerootTown_Text_TownSign::
	.string "LITTLEROOT TOWN\n"
	.string "A town that can't be shaded any hue.$"
